// Code generated by scripts/generate-types.sh from the backend API. DO NOT EDIT.
// Regenerate with: ./scripts/generate-types.sh --fetch
// Source: GET /api/v1/execution/device-targets

package devicetargets

var androidTargets = PlatformTargetConfig{
	DefaultPair: DevicePair{Model: "Pixel 7", Runtime: "Android 14"},
	AvailableRuntimes: []string{
		"Android 14",
	},
	AvailableModels: []string{
		"Pixel 7",
	},
	CompatibleRuntimes: map[string][]string{
		"Pixel 7": {"Android 14"},
	},
}

var iosTargets = PlatformTargetConfig{
	DefaultPair: DevicePair{Model: "iPhone 17 Pro Max", Runtime: "iOS 26.5"},
	AvailableRuntimes: []string{
		"iOS 26.5",
		"iOS 26.2",
		"iOS 18.5",
	},
	AvailableModels: []string{
		"iPhone 17 Pro Max",
		"iPhone Air",
		"iPhone 15",
		"iPhone 16",
		"iPad Pro 13-inch (M4)",
	},
	CompatibleRuntimes: map[string][]string{
		"iPhone 17 Pro Max":     {"iOS 26.5", "iOS 26.2"},
		"iPhone Air":            {"iOS 26.5", "iOS 26.2"},
		"iPhone 15":             {"iOS 18.5", "iOS 26.2"},
		"iPhone 16":             {"iOS 26.5", "iOS 18.5", "iOS 26.2"},
		"iPad Pro 13-inch (M4)": {"iOS 18.5", "iOS 26.2"},
	},
}

var platformTargets = map[string]*PlatformTargetConfig{
	"android": &androidTargets,
	"ios":     &iosTargets,
}
